"""remove_menu_item_fk

Revision ID: 3f10c1235080
Revises: 846d1cf0463a
Create Date: 2026-06-18 03:09:28.799574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f10c1235080'
down_revision: Union[str, Sequence[str], None] = '846d1cf0463a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('order_items_menu_item_id_fkey'), 'order_items', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('order_items_menu_item_id_fkey'), 'order_items', 'menu_items', ['menu_item_id'], ['id'])
    # ### end Alembic commands ###
