"""Add order_number and Notification

Revision ID: 66d541acaac2
Revises: 3f10c1235080
Create Date: 2026-06-18 05:05:32.107567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66d541acaac2'
down_revision: Union[str, Sequence[str], None] = '3f10c1235080'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('orders', sa.Column('order_number', sa.Integer(), nullable=True))
    op.create_unique_constraint('uq_canteen_order_number', 'orders', ['canteen_id', 'order_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_canteen_order_number', 'orders', type_='unique')
    op.drop_column('orders', 'order_number')
    op.drop_table('notifications')
    # ### end Alembic commands ###
