"""Add is_available to daily_specials

Revision ID: c282bc7008b3
Revises: 9ecf5532525a
Create Date: 2026-06-19 12:38:06.292752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c282bc7008b3'
down_revision: Union[str, Sequence[str], None] = '9ecf5532525a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_specials', sa.Column('is_available', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_specials', 'is_available')
    # ### end Alembic commands ###
