"""add location to vendor applications

Revision ID: d6a9b52c7967
Revises: d33c4c110963
Create Date: 2026-06-18 23:31:49.273382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6a9b52c7967'
down_revision: Union[str, Sequence[str], None] = 'd33c4c110963'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendor_applications', sa.Column('location', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendor_applications', 'location')
    # ### end Alembic commands ###
